language: node_js

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install sass
  - gem install compass

node_js:
  - '0.10'

before_script:
  - npm install -g bower grunt-cli karma
  - bower install

script: grunt

deploy:
  provider: divshot
  environment:
    master: development
    staging: staging
    production: production
    skip_cleanup: true
  api_key:
    secure: C4UMuYb7aDME6jcdMtwlWnVjRuohNo8eZCuYtqEpkh7FvSoKikQpgV6uJa7iXuVzMLAUhN+dnD+5ffWqO0CUTakBULRlxZObY59aS8Va8bBUpPOeBwHra5D5dxkh8s/bw2rlMH66EdmWT6779xyl8s/+TjsLRUfVBAg37jSKLsU=
